#!/bin/bash
# filter_annotated_vcf 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://wiki.dnanexus.com/Developer-Portal for tutorials on how
# to modify this file.

set -x

export SHELL="/bin/bash"

main() {
    mkdir input
    cd input
    for i in "${!vcf_fn[@]}"; do
        dx download $(dx describe --json "${vcf_fn[$i]}" | jq -r .id)
    done
    files=$(find . -name '*.gz')
    cat_string=""
    for f in $files; do
      if [[ $f == *gz ]]; then
        zcat $f | cut -f 3 > "$f"_1
        grep -v "#" "$f"_1 > "$f"_2
        tail -n +2 "$f"_2 > "$f"_3
        rm -f "$f"_1
        rm -f "$f"_2 
        cat_string=$cat_string" $f"_3
      fi
    done

    cat $cat_string > $out_filename
    f=$(dx upload "$out_filename" --brief)
    dx-jobutil-add-output marker_out "$f" --class=file
}
